courseProject/Controllers/CollectionController.cs
using courseProject.Models;
using courseProject.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace courseProject.Controllers
{
    [Authorize]
    public class CollectionController : Controller
    {
        private IItemInterface ItemInterface;
        private ApplicationDbContext db;
        private ICollectionInterface CollectionInterface;
        public CollectionController(IItemInterface III, 
            ApplicationDbContext _db,
            ICollectionInterface ici
            )
        {
            db = _db;
            ItemInterface = III;
            CollectionInterface = ici;
        }

        [AllowAnonymous]
        public IActionResult ShowCollection(int collectionId) {
            Collection? collection = db.Collections.Include(c => c.Creater).Include(c => c.Items)
                    .Where(c => c.Id == collectionId).FirstOrDefault();
            if(collection == null)
            {
                return View("Error");
            }
            return View("ShowCollection", collection);
        }

        public IActionResult CreateCollection(string createrId) => View(CollectionInterface.CreateCollection(createrId));

        [HttpPost]
        public IActionResult CreateCollection(CreateCollectionModel collection)
        {
            if (ModelState.IsValid)
            {
                User? creater = db.Users.Where(c => c.Id == collection.CreaterId).FirstOrDefault();
                Topic? topic = db.Topics.Where(c => c.Id == collection.TopicId).FirstOrDefault();
                if (creater != null && topic != null)
                {
                    Collection newCollection = new Collection()
                    {
                        Name = collection.Name,
                        Description = collection.Description,
                        StringFieldName1 = collection.StringFieldName1,
                        StringFieldName2 = collection.StringFieldName2,
                        StringFieldName3 = collection.StringFieldName3,
                        TextFieldName1 = collection.TextFieldName1,
                        TextFieldName2 = collection.TextFieldName2,
                        TextFieldName3 = collection.TextFieldName3,
                        IntFieldName1 = collection.IntFieldName1,
                        IntFieldName2 = collection.IntFieldName2,
                        IntFieldName3 = collection.IntFieldName3,
                        DateTimeFieldName1 = collection.DateTimeFieldName1,
                        DateTimeFieldName2 = collection.DateTimeFieldName2,
                        DateTimeFieldName3 = collection.DateTimeFieldName3,
                        BoolFieldName1 = collection.BoolFieldName1,
                        BoolFieldName2 = collection.BoolFieldName2,
                        BoolFieldName3 = collection.BoolFieldName3,
                        Creater = creater,
                        Topic = topic
                    };
                    db.Collections.AddRange(newCollection);
                    db.SaveChanges();
                    return RedirectToAction("ShowCollection", new { collectionId = newCollection.Id });
                }
                ModelState.AddModelError("", "Wrong Topic or Creater does not exist");
            }
            return View(CollectionInterface.CreateCollection(collection.CreaterId));
        }

        [HttpPost]
        public IActionResult Delete(int collectionId)
        {
            Collection? collection = db.Collections.Include(c => c.Creater).Where(c => c.Id == collectionId).FirstOrDefault();
            db.Collections.Remove(collection);
            db.SaveChanges();
            return RedirectToAction("Profile", "Account", new { userId = collection.Creater.Id});
            //будет работать только для профиля и перенаправлять в профиль
        }

        public IActionResult CreateItem(int collectionId) { return View(ItemInterface.CreateItem(collectionId)); }

        [HttpPost]
        public IActionResult CreateItem(CreateItemModel item)
        {
            if (ModelState.IsValid)
            {
                Collection collection = db.Collections.Where(c => c.Id == item.CollectionId).FirstOrDefault();
                List<Tag> tags = new List<Tag>();
                foreach(var tag in item.tags)
                {
                    Tag? tag1 = db.Tags.Where(c => c.Name == tag).FirstOrDefault();
                    if(tag1 == null)
                    {
                        Tag newTag = new Tag() { Name = tag };
                        db.Tags.Add(newTag);
                        tags.Add(newTag);
                    }
                    else
                    {
                        tags.Add(tag1);
                    }
                }
                Item newItem = new Item()
                {
                    Name = item.Name,
                    Collection = collection,
                    CreaterId = item.CreaterId,
                    Tags = tags,
                    StringFieldValue1 = item.StringFieldValue1,
                    StringFieldValue2 = item.StringFieldValue2,
                    StringFieldValue3 = item.StringFieldValue3,
                    TextFieldValue1 = item.TextFieldValue1,
                    TextFieldValue2 = item.TextFieldValue2,
                    TextFieldValue3 = item.TextFieldValue3,
                    IntFieldValue1 = item.IntFieldValue1,
                    IntFieldValue2 = item.IntFieldValue2,
                    IntFieldValue3 = item.IntFieldValue3,
                    DateTimeFieldValue1 = item.DateTimeFieldValue1,
                    DateTimeFieldValue2 = item.DateTimeFieldValue2,
                    DateTimeFieldValue3 = item.DateTimeFieldValue3,
                    BoolFieldValue1 = item.BoolFieldValue1,
                    BoolFieldValue2 = item.BoolFieldValue2,
                    BoolFieldValue3 = item.BoolFieldValue3
                };
                db.Items.Add(newItem);
                db.SaveChanges();
                return RedirectToAction("ShowCollection", new { collectionId = item.CollectionId });
            }
            return View(ItemInterface.CreateItem(item.CollectionId));
        }

        [HttpPost]
        public IActionResult DeleteItem(int itemId)
        {
            Item? item = db.Items.Include(c=>c.Collection).Where(c => c.Id == itemId).FirstOrDefault();
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("ShowCollection", new { collectionId = item.Collection.Id });
        }

        [AllowAnonymous]
        public IActionResult ShowItem(int itemId)
        {
            Item? item = db.Items.Include(c => c.Tags).Include(c => c.Collection.Creater).Include(c => c.Comments).Where(c => c.Id == itemId)
                .FirstOrDefault();
            if (item == null) { return View("Error"); }
            return View("ShowItem", item);
        }

        [HttpPost]
        public IActionResult CreateComment(CreateComment comment)
        {
            if (ModelState.IsValid)
            {
                Item item = db.Items.Where(c => c.Id == comment.ItemId).First();
                Comment newComment = new Comment() {
                    Text = comment.Text,
                    CreaterId = comment.CreaterId,
                    Item = item
                };
                db.Comments.Add(newComment);
                db.SaveChanges();
                return RedirectToAction("ShowItem", new { itemId = comment.ItemId });
            }
            return RedirectToAction("ShowItem", new { itemId = comment.ItemId });
        }
    }
}

courseProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using courseProject.Services;

namespace courseProject.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private IHomePageInterface HomePageInterface;

        public HomeController(ILogger<HomeController> logger, IHomePageInterface hpi) { 
            _logger = logger;
            HomePageInterface = hpi;
        }

        [AllowAnonymous]
        public IActionResult Index(string searchString, string id = "Item")
        {
            ViewBag.SearchString = searchString;
            return View(HomePageInterface.Collections(id, searchString));
        }

    }
}

courseProject/Views/Home/Index.cshtml
@model Dictionary<string, IEnumerable<object>>

<div class="bg-primary panel-body"><h4>Main Page</h4></div>
<form asp-controller="Home" asp-action="Index" method="get">
    <p>
        Search: <input type="text" name="searchString" value="@ViewBag.SearchString"/>
        <input type="submit" value="Filter" />
    </p>
</form>
<table>
    <tr>
        <td>
            <form asp-controller="Home" asp-action="Index" method="get">
                <input type="hidden" value="@ViewBag.SearchString" name="searchString" />
                <input type="hidden" value="Data" name="id" />
                <input class="btn btn-sm btn-primary" type="submit" value="Data" />
            </form>
        </td>
        <td>
            <form asp-controller="Home" asp-action="Index" method="get">
                <input type="hidden" value="@ViewBag.SearchString" name="searchString" />
                <input type="hidden" value="Items" name="id" />
                <input class="btn btn-sm btn-primary" type="submit" value="Items" />
            </form>
        </td>
        <td>
            <form asp-controller="Home" asp-action="Index" method="get">
                <input type="hidden" value="@ViewBag.SearchString" name="searchString" />
                <input type="hidden" value="Name" name="id" />
                <input class="btn btn-sm btn-primary" type="submit" value="Name" />
            </form>
        </td>
    </tr>
</table>

<div class="container">
    <ul class="nav nav-tabs" role="tablist">  
        <li class="nav-item">  
            <a class="nav-link active" data-toggle="tab" href="#collections">Collections</a>  
        </li> 
        <li class="nav-item">  
            <a class="nav-link" data-toggle="tab" href="#items">Items</a>  
        </li>
    </ul>  
    <div class="tab-content">
        <div id="collections" class="container tab-pane active">  
            <table class="table table-condensed table-bordered">
                <tr>
                    <th>Collection name</th>
                    <th>Creater Name</th>
                    <th>Topic</th>
                    <th>Description</th>
                    <th>Item Namber</th>
                </tr>
                @if(Model["collections"].Count() == 0 && Model["items"].Count() == 0){<tr><td>No content</td></tr>}
                @foreach(Collection collection in Model["collections"])
                {
                    <tr>
                        <td><a asp-controller="Collection" asp-action="ShowCollection" asp-route-collectionId=@collection.Id>@collection.Name</a></td>
                        <td><a asp-action="Profile" asp-controller="Account" asp-route-userId=@collection.Creater.Id>@collection.Creater.UserName</a></td>
                        <td>@collection.Topic.Name</td>
                        <td>@collection.Description</td>
                        <td>@collection.Items.Count()</td>
                        @if(User.IsInRole("Admin")){
                            <td><form asp-controller="Collection" asp-action="Delete" asp-route-collectionId="@collection.Id" method="post">
                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                            </form></td>
                        }
                    </tr>
                }
            </table>  
        </div>
        <div id="items" class="container tab-pane active">  
            <table class="table table-condensed table-bordered">
                <tr>
                    <th>Item name</th>
                    <th>Collection Name</th>
                    <th>Comments Namber</th>
                </tr>
                @foreach(Item item in Model["items"])
                {
                    <tr>
                        <td><a asp-controller="Collection" asp-action="ShowItem" asp-route-itemId=@item.Id>@item.Name</a></td>
                        <td><a asp-action="ShowCollection" asp-controller="Collection" asp-route-collectionId=@item.Collection.Id>@item.Collection.Name</a></td>
                        <td>@item.Comments.Count()</td>
                        @if(User.IsInRole("Admin")){
                            <td><form asp-controller="Collection" asp-action="DeleteItem" asp-route-itemId="@item.Id" method="post">
                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                            </form></td>
                        }
                    </tr>
                }
            </table> 
        </div>
    </div>
</div>
@if(User?.Identity?.IsAuthenticated ?? false)
{ <a class="nav-link text-dark" asp-controller="Collection" asp-action="CreateCollection" asp-route-createrId=@Context.Request.Cookies["userId"]>Create Collection</a> }

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>  
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>